using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NameGenerator
{
    List<string> takenNames = new List<string>();

    string[] femaleNames = new string[]{
        "Mary",
        "Helen",
        "Margaret", 
        "Anna",
        "Ruth",
        "Elizabeth",
        "Dorothy",
        "Marie",
        "Florence",
        "Mildred",
        "Alice",
        "Ethel",
        "Lillian",
        "Gladys",
        "Edna",
        "Frances",
        "Rose",
        "Annie",
        "Grace",
        "Bertha",
        "Emma",
        "Bessie",
        "Clara",
        "Hazel",
        "Irene",
        "Gertrude",
        "Louise",
        "Catherine", 
        "Martha",
        "Mabel",
        "Pearl",
        "Edith",
        "Esther",
        "Minnie",
        "Myrtle",
        "Ida",
        "Josephine",
        "Evelyn",
        "Elsie",
        "Eva",
        "Thelma",
        "Ruby",
        "Agnes",
        "Sarah",
        "Viola", 
        "Nellie", 
        "Beatrice", 
        "Julia", 
        "Laura", 
        "Lillie",
        "Lucille",
        "Ella", 
        "Virginia",
        "Mattie",
        "Pauline",
        "Carrie",
        "Alma",
        "Jessie", 
        "Mae", 
        "Lena", 
        "Willie",
        "Katherine", 
        "Blanche",
        "Hattie", 
        "Marion",
        "Lucy", 
        "Stella", 
        "Mamie",
        "Vera", 
        "Cora", 
        "Fannie", 
        "Eleanor", 
        "Bernice",
        "Jennie", 
        "Ann",
        "Leona",
        "Beulah", 
        "Lula", 
        "Rosa",
        "Ada", 
        "Ellen", 
        "Kathryn",
        "Maggie", 
        "Doris",
        "Dora",
        "Betty", 
        "Marguerite",
        "Violet", 
        "Lois", 
        "Daisy", 
        "Anne", 
        "Sadie", 
        "Susie",
        "Nora", 
        "Georgia", 
        "Maude",
        "Marjorie", 
        "Opal", 
        "Hilda", 
        "Velma" 
    };

    string[] maleNames = new string[]{
        "John",
        "William" ,
        "James" ,
        "George" ,
        "Charles" ,
        "Robert" ,
        "Joseph" ,
        "Frank" ,
        "Edward" ,
        "Thomas" ,
        "Henry" ,
        "Walter" ,
        "Harry",
        "Willie",
        "Arthur" ,
        "Albert" ,
        "Clarence",
        "Fred",
        "Harold", 
        "Paul" ,
        "Raymond", 
        "Richard" ,
        "Roy",
        "Joe",
        "Louis",
        "Carl",
        "Ralph",
        "Earl",
        "Jack" ,
        "Earnest",
        "David" ,
        "Samuel" ,
        "Howard",
        "Charlie", 
        "Francis" ,
        "Herbert",
        "Lawrence",
        "Theodore" ,
        "Alfred" ,
        "Andrew" ,
        "Sam" ,
        "Elmer", 
        "Eugene" ,
        "Leo" ,
        "Michael", 
        "Lee" ,
        "Herman", 
        "Anthony", 
        "Daniel" ,
        "Leonard",
        "Floyd" ,
        "Donald" ,
        "Kenneth" ,
        "Jesse" ,
        "Russell",
        "Clyde" ,
        "Oscar" ,
        "Peter" ,
        "Lester" ,
        "Leroy" ,
        "Ray" ,
        "Stanly",
        "Clifford",
        "Lewis" ,
        "Benjamin", 
        "Edwin" ,
        "Frederick",
        "Chester",
        "Claude",
        "Eddie",
        "Cecil" ,
        "Lloyd" ,
        "Jessie" ,
        "Martin",
        "Bernard", 
        "Tom",
        "Will", 
        "Norman",
        "Edgar",
        "Harvey", 
        "Ben" ,
        "Homer",
        "Luther",
        "Leon" ,
        "Melvin",
        "Philip",
        "Johnnie",
        "Jim" ,
        "Milton",
        "Everett", 
        "Allen" ,
        "Leslie",
        "Alvin",
        "Victor", 
        "Marvin",
        "Stephen", 
        "Alexander", 
        "Jacob" ,
        "Hugh" ,
        "Patrick"
    };

    string[] lastNames = new string[]{
        "Browne",
        "Chandler",
        "Nixon",
        "Gough",
        "Collier",
        "Farmer",
        "Howarth",
        "Lees",
        "Pollard",
        "Hope",
        "Blackburn",
        "Christie",
        "Rodgers",
        "Norton",
        "Sweeney",
        "Welch",
        "Benson",
        "Daly",
        "Ingram",
        "Swift",
        "Cairns",
        "Forbes",
        "Beattie",
        "Wallis",
        "Godfrey",
        "Donaldson",
        "Allison",
        "Pope",
        "Rowley",
        "Hanson",
        "Potts",
        "Blair",
        "Parkin",
        "Summers",
        "Sims",
        "Maguire",
        "Burnett",
        "Hilton",
        "Maxwell",
        "Fitzpatrick",
        "Storey",
        "Currie",
        "Cullen"
    };

    public string GenerateName(Suspect.Gender gender) {
        string firstName;
        string lastName;

        do {
            if (gender == Suspect.Gender.Female) {
                firstName = femaleNames[Random.Range(0, femaleNames.Length)];
            }
            else {
                firstName = maleNames[Random.Range(0, maleNames.Length)];
            }
        } while (takenNames.Contains(firstName));

        do {
            lastName = lastNames[Random.Range(0, lastNames.Length)];
        } while (takenNames.Contains(lastName));

        takenNames.Add(firstName);
        takenNames.Add(lastName);
        return firstName + " " + lastName;
    }
}
